### ISSUE TITLE
Not working with digital ocean

### ISSUE THREAD

**Issue by namanmeherra-iitbhu** [kyle-lanier-mscs/email-spoofer#1] opened 2021-11-17 17:49 UTC
caddy      | {"level":"error","ts":1637171317.4070487,"logger":"tls.obtain","msg":"will retry","error":"[spooftest.co.in] Obtain: [spooftest.co.in] solving challenges: presenting for challenge: adding temporary record for zone spooftest.co.in.: got error status: HTTP 403: [{Code:10000 Message:Authentication error}] (order=https://acme-v02.api.letsencrypt.org/acme/order/284682550/40423084360) (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":2.632135456,"max_duration":2592000}

caddy      | {"level":"error","ts":1637171317.4282274,"logger":"tls.obtain","msg":"will retry","error":"[click.spooftest.co.in] Obtain: [click.spooftest.co.in] solving challenges: presenting for challenge: adding temporary record for zone spooftest.co.in.: got error status: HTTP 403: [{Code:10000 Message:Authentication error}] (order=https://acme-v02.api.letsencrypt.org/acme/order/284682550/40423084490) (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":2.648178885,"max_duration":2592000}

**Comment by kyle-lanier-mscs** [comment] 2021-11-17 22:40
This repository, in its current version, is working for four separate domains on DO via integration with CloudFlare. The error presented above is an authentication error. Specifically, caddy is not able to authenticate with CloudFlare to create/modify DNS records in cloudflare.

Please confirm the following:
1) you have a cloudflare account
2) you have imported your domain, spooftest.co.in within your cloudflare account
3) you have replaced the nameservers for your domain provider with the nameservers provided by cloudflare
4) In your cloudflare account, for your imported spooftest.co.in domain, you have generated an api token to modify DNS
![image](https://user-images.githubusercontent.com/59059471/142293424-4d64fb3e-dd83-438a-9513-0cf20834a031.png)

5) you have confirmed your cloudflare token is functional
![image](https://user-images.githubusercontent.com/59059471/142293610-c6b0832e-d0cc-461d-9594-bfad29aed955.png)

7) Change the settings.env file for your copy of this repository, specifically you must change the following options to match your domain name and/or relay host.

For the Return-Path address, leave the username as "no-reply" and only change the domain name. Otherwise, the mail server may start to issue thousands of bounce messages and fill up your log files.

You MUST change the root domain name: DOMAIN=spooftest.co.in
You MUST change the tracking subdomain for GoPhish: TRACK_DOMAIN=click.spooftest.co.in
You MUST change the Return-Path address: RETURN_PATH_ADDRESS=no-reply@spooftest.co.in
You MUST change the Cloudflare API for editing DNS: CLOUDFLARE_API_TOKEN={YOUR CLOUDFLARE API TOKEN}

**Comment by kyle-lanier-mscs** [comment] 2021-11-17 23:07
Confirmed, the issue reported above is due to a denied authentication request to cloudflare. Confirmed, the correct steps above work successfully. Will consider a link in the readme to a video on youtube for better instructions.

Closing issue as unnecessary.

**Closed by kyle-lanier-mscs** 2021-11-17 23:07 UTC

**Comment by namanmeherra-iitbhu** [comment] 2021-11-18 08:43
> Confirmed, the issue reported above is due to a denied authentication request to cloudflare. Confirmed, the correct steps above work successfully. Will consider a link in the readme to a video on youtube for better instructions.
> 
> Closing issue as unnecessary.

which API token template should i use while generating the API token in cloudflare?

**Comment by namanmeherra-iitbhu** [comment] 2021-11-18 14:57
[
![Screenshot 2021-11-18 202612](https://user-images.githubusercontent.com/75215074/142439396-faa6fb74-13c7-44ea-8477-604da58cfaf7.jpg)
](url)
It's stuck here, please consider making a video tutorial if you can.
